version: "3.7"

services:
  lambda_job: 
    build: 
      context: ./extract_api_data
    volumes: 
      - ./:/${LAMBDA_TASK_ROOT}

    container_name: lambda_job
  
  terraform: 
    image: hashicorp/terraform:latest
    volumes: 
      - ./:/infra
    working_dir: /infra
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  