name: CI

on: [pull_request]

env:
  AWS_ACCESS_KEY_ID: ${{   secrets.AWS_ACCESS_KEY_ID   }}
  AWS_SECRET_ACCESS_KEY: ${{   secrets.AWS_SECRET_ACCESS_KEY  }}


jobs: 
    ci_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout repo
              uses: actions/checkout@v2

            - name: Spin up containers
              run: make up

            - name: Run CI test
              run: make ci

            - name: Stop container
              run: make down




